### ISSUE TITLE
carbon use error

### ISSUE THREAD

**Issue by kuafuRace** [chenling8523/go-demo#1]
https://github.com/LittleBugProducer/go-demo/blob/b04e09d2fb17a6ba35890b7c6b246efca7305fc9/carbon/main.go#L20
Here is the correct usage
```go
fmt.Println(time.Now().Format(carbon.RFC3339Format)) 
fmt.Println(time.Now().Layout(carbon.RFC3339Layout)) 
```

**Comment by chenling8523** [comment]
Thanks! 
There is no layout method for time.Time, guess you meaning this
```
fmt.Println(carbon.Now().Layout(carbon.RFC3339Layout))
fmt.Println(carbon.Now().Format(carbon.RFC3339Format))
```

Alongside, I have encountered some confusion. It appears that carbon.Layout() actually calls time.Format(), while carbon.Format() performs formatter encoding in its own distinct manner. Is this due to its original design?

**Comment by gouguoyin** [comment]
carbon.Layout() = time.Format()，the parameter of time.Format() is actually layout

**Comment by gouguoyin** [comment]
carbon.Now().Format("Y-m-d H:i:s") is inspired by php

**Comment by chenling8523** [comment]
Thank you for your response.
